spring:
  application:
      name: mghio-pay-provider
  cloud:
      config:
          uri: http://localhost:8888

eureka:
  instance:
    prefer-ip-address: true

server:
  port: 8081

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.mghio.mapper
