server:
  port: 8082

spring:
  application:
    name: mghio-ucenter-provider
  cloud:
    config:
      uri: http://localhost:8888

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.mghio.mapper

eureka:
  instance:
    prefer-ip-address: true
