spring:
  application:
      name: mghio-turbine-server
  cloud:
      config:
          uri: http://localhost:8888

eureka:
  instance:
    prefer-ip-address: true

server:
  port: 8031
turbine:
  app-config: mghio-ucenter-provider,mghio-pay-provider
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")




